- name: "Check if Burp CA exist"
  stat:
    path: /usr/local/share/ca-certificates/BurpCA.der
  register: burp_cert 
  become: true
  become_method: sudo
- name: "Download Burp CA certificate"
  command: 
    cmd: bash -c 'timeout 15 $(java -Djava.awt.headless=true -jar /usr/share/burpsuite/burpsuite.jar<<< "y") & sleep 10;curl http://localhost:8080/cert -o /tmp/cacert.der'
  when: burp_cert.stat.exists == False
- name: "Copy Burp cert"
  copy:
    src: /tmp/cacert.der
    dest: /usr/local/share/ca-certificates/BurpCA.der
  become: true
  become_method: sudo
  when: burp_cert.stat.exists == False
