- name: "Change firefox policies.json file"
  template:
    src: files/policies.json.j2
    dest: "/usr/share/firefox-esr/distribution/policies.json" # change settings file 
  become: true
  become_method: sudo
