---
# tasks file for setup-system
- name: "Copy a jpg file"
  copy:
    src: files/avatar.jpg
    dest: "{{ ansible_env.HOME }}/Desktop/"
- include: terminal.yml
- include: wordlist.yml
- include: pt_report.yml

