---
- name: "Copy wordlist"
  copy:
    src: files/wordlist
    dest: "{{ ansible_env.HOME }}/"
- name: "Unzip rockyou.txt"
  ansible.builtin.unarchive:
    src: "{{ ansible_env.HOME }}/wordlist/rockyou.txt.tar.gz"
    dest: "{{ ansible_env.HOME }}/wordlist/"
    remote_src: yes 
- name: "Remove rockyou tar file"
  file:
    path: "{{ ansible_env.HOME }}/wordlist/rockyou.txt.tar.gz"
    state: absent
